### ISSUE TITLE
DESeq2DS.R error as rownames_to_columns can't be used on res

### ISSUE THREAD

**Issue by tombisho** [isglobal-brge/dsOmics#21]
Hi,

Thanks for the recent fix to return the gene names. This works for edgeRDS but I get an error for DESeq2DS because the res object is not dataframe-like. This command fails:

```res <- tibble::rownames_to_column(res, "gene")```

So I guess another step is needed?

Thanks

Tom

**Comment by ESCRI11** [comment]
I solved it on the commit 50cfb00697e800a71a42f43d1482b884068007b2 , it now works as expected, however, as you mentioned on the DataSHIELD forums, the execution may break due to computation overload.
