### ISSUE TITLE
Dependency not available anymore: dummies 

### ISSUE THREAD

**Issue by ymarcon** [isglobal-brge/dsOmics#24]
dsOmics package installation fails because of the missing package 'dummies'

https://cran.r-project.org/web/packages/dummies/

**Comment by ymarcon** [comment]
Workaround:

```
remotes::install_version("dummies", version="1.5.6")
```

**Comment by ESCRI11** [comment]
Hello Yannick, sorry for the late reply.

I have removed the dummies dependency and added an auxiliary function to handle the on hot encodings. Please feel free to use tag '1.0.11' for the new release.

Thanks for reporting the problem.
