### ISSUE TITLE
Issue with DGE analysis using ds.limma

### ISSUE THREAD

**Issue by FrancescoAnzillotti** [isglobal-brge/dsOmics#25]
Hi, I’m having some issues using the ds.limma function. Specifically, when following :  
https://isglobal-brge.github.io/resource_bookdown/differential-gene-expression-dge-analysis.html
my output is:
```r
"Command 'limmaDS2(rse, res, 2L, NULL, 2, NULL, FALSE, \"none\")' failed on 'study1': 
Error while evaluating 'dsOmics::limmaDS2(rse, res, 2L, NULL, 2, NULL, FALSE, \"none\")' -> 
Error in dsOmics::limmaDS2(rse, res, 2L, NULL, 2, NULL, FALSE, \"none\") : \n  object 'Set.counts' not found\n"
```
Troubleshooting:  
* I locally downloaded the dataset used in the guide above  
* I downloaded the code of the ds.limma function (client side) and limmaDS function (server side) and combined them together to run locally on the downloaded dataset. 
    
Running locally produces the expected output (the analysis is correctly executed).
What seems to be the problem is the connection between the two functions when operating in client-server mode, specifically this piece of code when calling limmaDS. 
```r
Set <- eval(parse(text=Set), envir = parent.frame())
```

**Comment by isglobal-brge** [comment]
Hi Francesco, 

Are you using DSlite to test the package? how do you "combine" the functions together to run locally? you should not have access to limmaDS function since it should be in your server ... what server are you using?

Juan

**Comment by FrancescoAnzillotti** [comment]
Hi Juan, 
From the ds.limma function (client side https://github.com/isglobal-brge/dsOmicsClient/tree/master/R) I removed the calls to the limmaDS function (server side) and replaced them with the code found here: https://github.com/isglobal-brge/dsOmics/tree/master/R. 

The real issue however is that I’m are not able to reproduce the results of : https://isglobal-brge.github.io/resource_bookdown/differential-gene-expression-dge-analysis.html. 
My code is the following (copy and paste of what is written in the guide):  
```r
builder = newDSLoginBuilder()
builder$append(server = "study1", url = "https://opal-demo.obiba.org/", 
               user = "dsuser", password = "P@ssw0rd", #the password in the guide doesn't work, this is a password from an older version of the tutorial
               resource = "RSRC.tcga_liver", driver = "OpalDriver")
logindata <- builder$build()
conns <- DSI::datashield.login(logins = logindata, assign = TRUE, symbol = "res")
datashield.assign.expr(conns, symbol = "rse", expr = quote(as.resource.object(res)))
ans.gender = ds.limma(model = ~ gdc_cases.demographic.gender, Set = "rse", type.data = "RNAseq", sva = FALSE)
```
And i get : 
```r
<error/rlang_error>
Error:
! There are some DataSHIELD errors:
✖ study1: [Client error: (400) Bad Request] No such DataSHIELD 'ASSIGN' method with name: limmaDS

---
Backtrace:
    ▆
 1. └─dsOmicsClient::ds.limma(...)
 2.   └─DSI::datashield.assign.expr(datasources, "res", calltext)
 3.     └─cli::cli_abort(...)
 4.       └─rlang::abort(...)
```

Francesco

**Comment by ESCRI11** [comment]
Hello @FrancescoAnzillotti, the issue is solved. Please see my response on DataSHIELD forums, thank you for your patience. 

https://datashield.discourse.group/t/issue-with-dge-analysis-using-ds-limma/1119/2?u=xescriba
